### ISSUE TITLE
Constants should be ALL_UPPERCASE, using the const keyword and on top of your program

### ISSUE THREAD

**Issue by incredibleLeitman** [Layusmen/TileCostCalculator#1]
https://github.com/Layusmen/TileCostCalculator/blob/408bf608fc06bffcf25bc234469241c1dc4f80e3/TileCostCalculator/TileCostCalculator/Program.cs#L24-L25

**Comment by Layusmen** [comment]
done as suggested

**Comment by mayisa87** [comment]
Seems you oversaw this?

https://github.com/Layusmen/TileCostCalculator/blob/9616dcfb3ed81066373a34319bfab6dd065a3b46/TileCostCalculator/TileCostCalculator/Program.cs#L75-L76

Please define constants instead of variables and move it at the beginning of your program.
