### ISSUE TITLE
Nice to have, but makes it more complicated than necessary

### ISSUE THREAD

**Issue by mayisa87** [Layusmen/TileCostCalculator#12]
https://github.com/Layusmen/TileCostCalculator/blob/ff15584d4c4547173e5ef21ef6b79992329f622a/TileCostCalculator/TileCostCalculator/Program.cs#L72-L74

In general, it is highly recommended to avoid duplicated code. But you will always have like a dot in your texts  or a dollar sign. It makes it just way more complicated to always use variables for those texts. Just write the text ;) Imagine a program with thousands of text lines somewhere in code... way to complicated ;)

**Comment by Layusmen** [comment]
Alright. I will keep to that.
