### ISSUE TITLE
Remove if, as invalid shape type is already handled in while loop

### ISSUE THREAD

**Issue by mayisa87** [Layusmen/TileCostCalculator#13]
https://github.com/Layusmen/TileCostCalculator/blob/ff15584d4c4547173e5ef21ef6b79992329f622a/TileCostCalculator/TileCostCalculator/Program.cs#L67-L70

You already have a while loop to handle wrong inputs, so this else block will never be executed at all, as your loop will force user to enter a valid shape type anyway.

So you could delete the else block compeltely.

**Comment by Layusmen** [comment]
Alright. Thanks.
