### ISSUE TITLE
Chain statements when appropriate

### ISSUE THREAD

**Issue by incredibleLeitman** [Layusmen/TileCostCalculator#2]
If you don't use the temporary value of a statement or calculation, there is no point in storing it,
unless you want to use it for debugging purposes ☝️ 

So instead of 
https://github.com/Layusmen/TileCostCalculator/blob/408bf608fc06bffcf25bc234469241c1dc4f80e3/TileCostCalculator/TileCostCalculator/Program.cs#L12-L15

you could just chain ReadLine and ToUpper:
```string shapeOfRoom = Console.ReadLine().ToUpper();```

**Comment by Layusmen** [comment]
done as suggested
