### ISSUE TITLE
remove unnecessary usings

### ISSUE THREAD

**Issue by incredibleLeitman** [Layusmen/TileCostCalculator#3]
Do you know what this using stands for? 
https://github.com/Layusmen/TileCostCalculator/blob/408bf608fc06bffcf25bc234469241c1dc4f80e3/TileCostCalculator/TileCostCalculator/Program.cs#L2
If not or if you don't have added it manually you possible can remove it.

You should get into the habit of cleaning your code everytime before commiting it or sending it to us.
This also include checking if there are usings you probably don't really need -> You can use the shortcut "Ctrl+K+D" regularly

**Comment by Layusmen** [comment]
Thanks for the observation. Corrected.
