### ISSUE TITLE
This calculation does not make much sense

### ISSUE THREAD

**Issue by incredibleLeitman** [Layusmen/TileCostCalculator#4]
https://github.com/Layusmen/TileCostCalculator/blob/408bf608fc06bffcf25bc234469241c1dc4f80e3/TileCostCalculator/TileCostCalculator/Program.cs#L26-L28
Here you divide the amount of square feet the team can lay down in one hour by the price per hour 🤔 

Whereas what you should do is divide the total area of the shape by the "squareFeetPerHour" to get the hours the team needs
and then multiply that by the cost per hour to get the labor price.
In fact, it is not needed to prompt for the size of tiles because the price is given per square feet and not tile.

Maybe this confusion happened because of bad naming:
"squareFeet" is not a good variable name because it is missing the point of what its actually representing,
same as "perHour"

**Comment by Layusmen** [comment]
I did the calculation as you said. At the base, I completed the calculation. If you check toward the end of the code, the calculation is completed.

**Comment by Layusmen** [comment]
Here is the completion. However, I will change the suggested naming though.
double labourCost;
            
            labourCost = area * workDone;
            Console.WriteLine("The labor cost is: $" + labourCost);

**Comment by Layusmen** [comment]
Here is the completion. However, I will change the suggested naming though.


        double labourCost;
        labourCost = area * workDone;
        Console.WriteLine("The labor cost is: $" + labourCost);

**Comment by incredibleLeitman** [comment]
"workDone" is still not a very good name :S 
Just from reading it I have no clue what this variable is used for 🤷 

"hoursNeeded" or something like this would be better imho

**Comment by Layusmen** [comment]
Corrected. Thanks for the observation

**Comment by mayisa87** [comment]
I think what Michael meant addtionally was, that the exercise request, that user enters the costs per Unit, and this implicates the costs per square feet. But maybe the excercise description is a bit misleading?

Of course, if you do it this way, it is a very detailed calculation, as you got the cost per Tile and the size of Tile and calculate how much tiles are needed. This is also a way to do it ;)

**Comment by incredibleLeitman** [comment]
Yeah, your interpretation is also fine, now that the calculation works 👍  :D
